import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Customer } from './store/customer.model';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const customers = [
      {
        id: '4',
        name: 'John Doe',
        email: 'john@sgtpeppers.org',
        house: '',
        street: '',
        city: '',
        zip: '35000',
        coordinates: [],
      },
      {
        id: '1',
        name: 'Paul Doe',
        email: 'paul@sgtpeppers.org',
        house: '',
        street: '',
        city: '',
        zip: '0132',
        coordinates: [],
      },
      {
        id: '2',
        name: 'Ringo Doe',
        email: '',
        house: '',
        street: 'Abbey Rd.',
        city: '',
        zip: '35000',
        coordinates: [25.26379072264602, 54.698433832952944],
        friendlyCoordinates: '25.2637, 54.6984',
      },
      {
        id: '3',
        name: 'George Taxman',
        email: '',
        house: '15',
        street: 'Gedimino pr.',
        city: 'Vilnius',
        zip: '35000',
        coordinates: [],
      },
      {
        id: '2344',
        name: 'John Doe',
        email: 'john@sgtpeppers.org',
        house: '',
        street: '',
        city: '',
        zip: '35000',
        coordinates: [],
      },
      {
        id: '15345',
        name: 'Paul Doe',
        email: 'paul@sgtpeppers.org',
        house: '',
        street: '',
        city: '',
        zip: '0132',
        coordinates: [],
      },
      {
        id: '2235',
        name: 'Ringo Doe',
        email: '',
        house: '',
        street: 'Abbey Rd.',
        city: '',
        zip: '35000',
        coordinates: [25.26379072264602, 54.698433832952944],
        friendlyCoordinates: '25.2637, 54.6984',
      },
      {
        id: '2342455',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '65435',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '2455',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '545645645',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '5452424',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '575755',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '5767757',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '63463465',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '48684685',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '735735',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '3573575',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '535735735',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '5685685',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '524624624',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '45745745',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '5253525',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '51354135',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '143141345',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '142412415',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '13654635',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '51243546',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '56453243545',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '324565',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '58765',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '897655',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '35673575',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '2352355',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
      {
        id: '46574574755',
        name: 'Walrus',
        email: '',
        house: '',
        street: '',
        city: '',
        zip: '',
        coordinates: [],
      },
    ];
    return { customers };
  }

  // genId(customers: Customer[]): number {
  //   return customers.length > 0
  //     ? Math.max(...customers.map((customer) => customer.id)) + 1
  //     : 11;
  // }
}
